### ISSUE TITLE
Learning goals don't align with the readme

### ISSUE THREAD

**Issue by TylerTaylor** [learn-co-curriculum/python-p4-tcp-http-and-websocket#1]
### Canvas Link

https://learning.flatironschool.com/courses/6182/pages/tcp-http-and-websocket?module_item_id=486877

### Concern

It states at the top: **Learning Goals** - Create websocket connections between clients and servers to improve our applications' performance.

Then it has 5 sentences total about websockets.

### Suggested Changes

I feel like this one should be marked "Optional" as well as remove the learning goals. They may now understand what websockets are, but definitely not how to use them.

**Comment by professor-ben** [comment]
This is a good point! There was more we wanted to do here, but we're working on building something out for phase 5. I want to make sure there's some coverage of TCP and HTTP for the students before they move into Phase 5 and their job search, but I can label this a mini lesson (as we did with lambdas).
