### ISSUE TITLE
What distinguishes WebSocket and TCP?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p4-tcp-http-and-websocket#2]
### Canvas Link

https://my.learn.co/courses/654/pages/mini-lesson-tcp-http-and-websocket?module_item_id=83864

### Concern

This reading doesn't really distinguish why WebSocket is better than a TCP connection. 

All the reading implies is that both types of connections are stateful, but we don't talk about why WebSocket is faster than a traditional TCP.

If we can add some language about what distinguishes a WebSocket from a traditional TCP connection, I think it will really enhance students' comprehension of the topic.

**Comment by professor-ben** [comment]
Added a paragraph for context- let me know if you think we're still a little short on detail.

Thanks,
Ben

**Comment by Matt-Eva** [comment]
Hey Ben! This looks great.

I was hoping we could add a little more language surrounding the difference between a traditional TCP connection and a WebSocket connection as well. Something like:

> Traditional TCP connections require developers to write their own transfer protocols. While this allows for customization on the developer's part - which is necessary in some niche circumstances - by and large it makes working with TCP slower and more difficult.
> 
> WebSocket solves this problem by establishing TCP connections with its own standardized, high-level communication protocol. This allows developers to set up WebSockets without having to configure a TCP protocol themselves.
> 
> This standardization also solves another problem: If a developer has set up an application to use a custom TCP protocol, any servers or clients that want to communicate with that application will need to use the same custom protocol.
> 
> WebSocket's standardized protocol is supported by all modern browsers and servers, which makes it easy to connect your app to other servers and clients as needed, without having to go through the configuration process all over again.


I'm still learning about this technology, so please disregard any erroneous statements above, and include any relevant differences that I didn't mention. Hope this is helpful!
